package hr.algebra.verbose_couscous.hmi.home;

import hr.algebra.verbose_couscous.bll.services.IDataService;
import hr.algebra.verbose_couscous.dal.models.Actor;
import hr.algebra.verbose_couscous.dal.models.Director;
import hr.algebra.verbose_couscous.dal.models.Genre;
import hr.algebra.verbose_couscous.dal.models.Movie;

/**
 *
 * @author remi
 */
public class MoviePanel extends javax.swing.JPanel {

    private final IDataService dataService;

    public MoviePanel(IDataService dataService) {
        this.dataService = dataService;
        initComponents();
        LoadMovies();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane_Movies = new javax.swing.JScrollPane();
        Label_MovieName = new javax.swing.JLabel();
        ScrollPane_Actors = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ScrollPane_Directors = new javax.swing.JScrollPane();
        TextField_Description = new javax.swing.JTextField();
        Label_PublishedDate = new javax.swing.JLabel();
        Label_Duration = new javax.swing.JLabel();
        Label_Year = new javax.swing.JLabel();

        Label_MovieName.setText("jLabel1");

        jLabel2.setText("Actors");

        jLabel3.setText("Directors");

        TextField_Description.setText("jTextField1");

        Label_PublishedDate.setText("jLabel4");

        Label_Duration.setText("jLabel4");

        Label_Year.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(ScrollPane_Movies,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        308,
                                        Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(Label_Year,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        158,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Label_PublishedDate,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        217,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Label_Duration,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        120,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(ScrollPane_Actors)
                                                        .addComponent(jLabel2,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                245,
                                                                Short.MAX_VALUE))
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ScrollPane_Directors)
                                                        .addComponent(jLabel3,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)))
                                        .addComponent(Label_MovieName,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(TextField_Description))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ScrollPane_Movies)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Label_MovieName,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        47,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Label_PublishedDate,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label_Duration,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Label_Year,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_Description,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        123,
                                        Short.MAX_VALUE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                26,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                26,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ScrollPane_Actors,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(ScrollPane_Directors,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Duration;
    private javax.swing.JLabel Label_MovieName;
    private javax.swing.JLabel Label_PublishedDate;
    private javax.swing.JLabel Label_Year;
    private javax.swing.JScrollPane ScrollPane_Actors;
    private javax.swing.JScrollPane ScrollPane_Directors;
    private javax.swing.JScrollPane ScrollPane_Movies;
    private javax.swing.JTextField TextField_Description;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void LoadMovies() {

        for (Movie movie : dataService.selectAll(Movie.class))
            ScrollPane_Movies.add(new ModelPanel<Movie>(movie));
    }

    private void LoadMovie(Movie movie) {

        Label_MovieName.setText(movie.Name);
        Label_Year.setText(String.valueOf(movie.Year));
        Label_PublishedDate.setText(movie.getPublishedDate());
        Label_Duration.setText(String.valueOf(movie.Duration));
        TextField_Description.setText(movie.Description);

        for (Genre genre : movie.getGenres())
            continue;
        // ScrollPane_Genres.add(new ModelPanel<Genre>(genre));
        for (Actor actor : movie.getActors())
            ScrollPane_Actors.add(new ModelPanel<Actor>(actor));
        for (Director director : movie.getDirectors())
            ScrollPane_Directors.add(new ModelPanel<Director>(director));
    }
}
