package hr.algebra.verbose_couscous.hmi.login;

import hr.algebra.verbose_couscous.bll.services.IAuthenticationService;

/**
 *
 * @author remi
 */
public class SignupPanel extends javax.swing.JPanel {

    private final IAuthenticationService authenticationService;

    private final Runnable onLoggedIn;

    public SignupPanel(IAuthenticationService authenticationService, Runnable onLoggedIn) {
        this.authenticationService = authenticationService;
        this.onLoggedIn = onLoggedIn;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
